chrome_crawling:
  # ディレクトリを指定するとその配下の Dockerfile を取得して実行する
  build: ./
  # `$ docker ps` 時に NAME として見える名前
  container_name: chrome_crawling
  # 勝手に終了しないよう設定しておく
  command: tail -f /dev/null
  # `$ docker exec -it chrome_crawling bash` でアタッチした際のカレントディレクトリとなる
  working_dir: /root/app/
  # ボリュームのマウント
  volumes:
    - ./:/root/app/
